-- lua/modules/themes.lua
local M = {}

-- All available themes collection (84 unique themes)
M.all_themes = {
  -- Your Custom Themes
  "aurora",
  "cherry_blossom",
  "cyberpunk_neon",
  "dracula_pro",
  "matrix_code",
  "monokai_pro",
  "ocean_depths",
  "pastel_dream",
  "retro_wave",
  "tokyo_rain",
  "volcanic_ash",

  -- NvChad Default Themes
  "aquarium",
  "ashes",
  "ayu_dark",
  "ayu_light",
  "bearded-arc",
  "blossom_light",
  "catppuccin",
  "chadracula",
  "chadracula-evondev",
  "chadtain",
  "chocolate",
  "dark_horizon",
  "decay",
  "doomchad",
  "everblush",
  "everforest",
  "everforest_light",
  "flexoki",
  "flexoki-light",
  "github_dark",
  "github_light",
  "gruvbox",
  "gruvbox_light",
  "gruvchad",
  "jabuti",
  "kanagawa",
  "material-darker",
  "material-lighter",
  "melange",
  "mito-laser",
  "monekai",
  "monochrome",
  "mountain",
  "nano-light",
  "nightfox",
  "nightlamp",
  "nightowl",
  "nord",
  "oceanic-light",
  "oceanic-next",
  "one_light",
  "onedark",
  "onenord",
  "onenord_light",
  "oxocarbon",
  "palenight",
  "pastelDark",
  "pastelbeans",
  "penumbra_dark",
  "penumbra_light",
  "poimandres",
  "radium",
  "rosepine",
  "rosepine-dawn",
  "solarized_dark",
  "solarized_osaka",
  "sweetpastel",
  "tokyodark",
  "tokyonight",
  "tomorrow_night",
  "tundra",
  "vscode_dark",
  "wombat",
  "yoru",
}

-- Curated favorites for quick toggling
M.favorites = {
  "onedark",
  "gruvchad",
  "catppuccin",
  "nord",
  "rosepine",
  "tokyodark",
  "everforest",
  "oxocarbon",
  "palenight",
  "chadracula",
  "kanagawa",
  "tokyonight",
  "github_dark",
  "nightowl",
  "dracula_pro",
  "cyberpunk_neon",
  "matrix_code",
  "tokyo_rain",
}

-- Dark themes only
M.dark = {
  "aurora",
  "cyberpunk_neon",
  "dracula_pro",
  "matrix_code",
  "monokai_pro",
  "ocean_depths",
  "retro_wave",
  "tokyo_rain",
  "volcanic_ash",
  "aquarium",
  "ashes",
  "ayu_dark",
  "bearded-arc",
  "catppuccin",
  "chadracula",
  "chadracula-evondev",
  "chocolate",
  "dark_horizon",
  "decay",
  "doomchad",
  "everblush",
  "everforest",
  "github_dark",
  "gruvbox",
  "gruvchad",
  "jabuti",
  "kanagawa",
  "material-darker",
  "melange",
  "monekai",
  "monochrome",
  "mountain",
  "nightfox",
  "nightlamp",
  "nightowl",
  "nord",
  "oceanic-next",
  "onedark",
  "onenord",
  "oxocarbon",
  "palenight",
  "pastelbeans",
  "pastelDark",
  "penumbra_dark",
  "poimandres",
  "radium",
  "rosepine",
  "solarized_dark",
  "solarized_osaka",
  "sweetpastel",
  "tokyodark",
  "tokyonight",
  "tomorrow_night",
  "tundra",
  "vscode_dark",
  "wombat",
  "yoru",
}

-- Light themes only
M.light = {
  "cherry_blossom",
  "pastel_dream",
  "ayu_light",
  "blossom_light",
  "everforest_light",
  "flexoki-light",
  "github_light",
  "gruvbox_light",
  "material-lighter",
  "nano-light",
  "oceanic-light",
  "one_light",
  "onenord_light",
  "penumbra_light",
  "rosepine-dawn",
}

return M
